# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  test_node
resources:
- repo: self
variables:
  # imageRepository: 'https://github.com/dhawalepraful1310/NodeJs_Demo.git'
  containerRegistry: 'nodedeployapp.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  dockerRegistryServiceConnection: '1964360c-68cd-442c-a83b-68c7a0218a6f'
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    # repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(tag)

- upload: manifests
  artifact: manifests
  