apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment
 # namespace: url
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: prafuldhawale1310/hello-world
          name: app
          ports:
            - containerPort: 5000
         
-- 
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
 # namespace: app
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
  selector:
    app: app
          
