apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app
 # namespace: app
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31000
  selector:
    app: app
